select = ["E", "F", "W", "Q", "I"]

ignore = ["E203"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Restrict line length to 120
line-length = 120

# Exclude specific files from linting
exclude = ["readme.md"]