[supervisord]
nodaemon=true
logfile=/var/log/fragment/supervisord.log
childlogdir=/var/log/fragment
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:pulseaudio]
command=/workspace/fragment/docker/start-fragment.sh pulseaudio
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/var/log/fragment/pulseaudio.out.log
stderr_logfile=/var/log/fragment/pulseaudio.err.log

[program:xorg]
command=/workspace/fragment/docker/start-fragment.sh xorg
autostart=true
autorestart=true
startretries=10
startsecs=2
priority=10
stdout_logfile=/var/log/fragment/xorg.out.log
stderr_logfile=/var/log/fragment/xorg.err.log

[program:window_manager]
command=/workspace/fragment/docker/start-fragment.sh wm
autostart=true
autorestart=true
startsecs=2
priority=20
stdout_logfile=/var/log/fragment/wm.out.log
stderr_logfile=/var/log/fragment/wm.err.log

[program:vnc]
command=/workspace/fragment/docker/start-fragment.sh vnc
autostart=true
autorestart=true
startsecs=2
priority=30
stdout_logfile=/var/log/fragment/vnc.out.log
stderr_logfile=/var/log/fragment/vnc.err.log

[program:fragment]
command=/workspace/fragment/docker/start-fragment.sh fragment
autostart=true
autorestart=true
startsecs=5
priority=40
stdout_logfile=/var/log/fragment/fragment.out.log
stderr_logfile=/var/log/fragment/fragment.err.log

