name: Lint, Format, and Bump Version

on:
  pull_request:

jobs:
  lint-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install ruff bump2version

      - name: Run Ruff Linting and Formatting
        run: |
          # Run Ruff to automatically fix issues (ignoring errors)
          ruff check . --fix || true
          # Run Ruff again to ensure formatting is correct
          ruff format .

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code linted by Ruff'

      - name: Bump Version
        # This runs a minor bump. Change "minor" to "patch" or "major" as needed.
        run: bump2version minor

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code version bumped'
