name: Lint, Format, Test, and Conditional Version Bump

on:
  pull_request:

jobs:
  lint-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PATCH_THRESHOLD: 250
      MINOR_THRESHOLD: 2000

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Use full history so that git diff can compare

      - name: Set Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install ruff bump2version pytest pytest-html-reporter

      - name: Run Ruff Linting and Formatting
        run: |
          # Run Ruff to automatically fix issues (ignoring errors)
          ruff check . --fix || true
          # Run Ruff again to ensure formatting is correct
          ruff format .

      - name: Auto Commit Changes (Ruff)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code linted by Ruff'

      - name: Run Python Unit Tests
        run: pytest ./tests --html-report=./reports/report.html

      - name: Determine Bump Level
        id: bump_level
        shell: bash
        run: |
          # Compare the current commit with the previous commit.
          DIFF_OUTPUT=$(git diff --shortstat HEAD^)
          echo "Diff stats: $DIFF_OUTPUT"
          
          # Extract numbers for insertions and deletions.
          insertions=$(echo "$DIFF_OUTPUT" | grep -oP '\d+(?= insertion)' || echo 0)
          deletions=$(echo "$DIFF_OUTPUT" | grep -oP '\d+(?= deletion)' || echo 0)
          total=$((insertions + deletions))
          echo "Total changes (insertions + deletions): $total"

          if [ "$total" -lt "$PATCH_THRESHOLD" ]; then
            echo "Bump level: patch"
            echo "level=patch" >> $GITHUB_OUTPUT
          elif [ "$total" -ge "$PATCH_THRESHOLD" ] && [ "$total" -lt "$MINOR_THRESHOLD" ]; then
            echo "Bump level: minor"
            echo "level=minor" >> $GITHUB_OUTPUT
          else
            echo "Bump level: major"
            echo "level=major" >> $GITHUB_OUTPUT
          fi

      - name: Bump Version Accordingly
        run: |
          echo "Using bump level: ${{ steps.bump_level.outputs.level }}"
          bump2version ${{ steps.bump_level.outputs.level }}

      - name: Auto Commit Changes (Version)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code version bumped'