name: Lint, Format, and Bump Version

on:
  pull_request:

jobs:
  lint-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install ruff bump2version

      - name: Run Ruff Linting and Formatting
        run: |
          # Run Ruff to automatically fix issues (ignoring errors)
          ruff check . --fix || true
          # Run Ruff again to ensure formatting is correct
          ruff format .

      - name: Auto Commit Changes (Ruff)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code linted by Ruff'

      - name: Bump Version
        run: bump2version patch

      - name: Auto Commit Changes (Version)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Code version bumped'