name: Lint, Format, and Auto-fix Python Code

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint autopep8 black

      - name: Run pylint to check for issues
        id: lint
        run: |
          pylint **/*.py --rcfile=.pylintrc-cicd > pylint_output.txt || true
          cat pylint_output.txt

      - name: Apply autopep8 fixes
        run: |
          autopep8 --in-place --aggressive --aggressive **/*.py

      - name: Run black for code formatting
        run: black .

      - name: Check for changes after formatting
        id: check_diff
        run: |
          if git diff --name-only HEAD | grep -E '\.py$'; then
            echo "true" > has_changes.txt
          else
            echo "false" > has_changes.txt
          fi
          echo "has_changes=$(cat has_changes.txt)" >> $GITHUB_ENV

      - name: Create fix branch
        if: env.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}-linting-fixes-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Auto-fix formatting issues with black and autopep8"
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: env.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
          base: ${{ github.event.pull_request.base.ref }}
          title: "Auto-fix formatting issues with black and autopep8"
          body: |
            This PR includes auto-fix changes for Python formatting issues detected by pylint and fixed by black and autopep8.
            Please review the changes and merge if they are acceptable.
