name: Lint and Commit

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install ruff
      - run: |
          ruff check . --fix
#          ruff fix .
#          ruff format .
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: 'Code linted by Ruff'