name: Create Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history for tagging

      - name: Set Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create Git Tag
        run: |
          VERSION=$(python -c "from version import __version__; print(__version__)")
          echo "Tagging version: $VERSION"
          git tag -a "v$VERSION" -m "Version $VERSION"

      - name: Push Git Tag
        run: git push origin --tags